package com.sparta.is.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;


public class modelByakushiki extends ModelBase
{
    //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer RightShoulderGuardTop;
    ModelRenderer RightShoulderGuardFrontBack;
    ModelRenderer RightFrontIncline1;
    ModelRenderer RightFrontIncline2;
    ModelRenderer RightFrontIncline3;
    ModelRenderer RightFrontIncline4;
    ModelRenderer RightFrontIncline5;
    ModelRenderer RightFrontIncline6;
    ModelRenderer RightBackIncline1;
    ModelRenderer RightBackIncline2;
    ModelRenderer RightBackIncline3;
    ModelRenderer RightBackIncline4;
    ModelRenderer RightBackIncline5;
    ModelRenderer RightBackIncline6;
    ModelRenderer RightJointGuard1;
    ModelRenderer RightJointGuard2;
    ModelRenderer RightJointGuard3;
    ModelRenderer RightJointGuard4;
    ModelRenderer BackTop;
    ModelRenderer BackMiddle;
    ModelRenderer Abdomen;
    ModelRenderer FrontMiddleRight;
    ModelRenderer FrontMiddleLeft;
    ModelRenderer Waist;
    ModelRenderer LeftArmBase;
    ModelRenderer LeftArmVent;
    ModelRenderer LeftArmGuardTop;
    ModelRenderer LeftArmGuardFront;
    ModelRenderer LeftArmGuardBack;
    ModelRenderer RightArmBase;
    ModelRenderer RightArmVent;
    ModelRenderer RightArmGuardTop;
    ModelRenderer RightArmGuardFront;
    ModelRenderer RightArmGuardBack;
    ModelRenderer LeftLegBase;
    ModelRenderer LeftLegBaseSide;
    ModelRenderer LeftLegBaseFrontTop;
    ModelRenderer LeftLegBaseInside;
    ModelRenderer LeftLegBaseOutside;
    ModelRenderer FootJoint1;
    ModelRenderer FootJoint2;
    ModelRenderer FootJoint3;
    ModelRenderer FootJoint4;
    ModelRenderer RightLegBase;
    ModelRenderer RightLegBaseSide;
    ModelRenderer RightLegBaseFrontTop;
    ModelRenderer RightLegBaseInside;
    ModelRenderer RightLegBaseOutside;
    ModelRenderer RightFootJoint1;
    ModelRenderer RightFootJoint2;
    ModelRenderer RightFootJoint3;
    ModelRenderer RightFootJoint4;
    ModelRenderer HelmetBack;
    ModelRenderer HelmetLeft;
    ModelRenderer HelmetRight;
    ModelRenderer ShoulderGuardTop;
    ModelRenderer ShoulderGuardFrontBack;
    ModelRenderer FrontIncline1;
    ModelRenderer FrontIncline2;
    ModelRenderer FrontIncline3;
    ModelRenderer FrontIncline4;
    ModelRenderer FrontIncline5;
    ModelRenderer FrontIncline6;
    ModelRenderer BackIncline1;
    ModelRenderer BackIncline2;
    ModelRenderer BackIncline3;
    ModelRenderer BackIncline4;
    ModelRenderer BackIncline5;
    ModelRenderer BackIncline6;
    ModelRenderer JointGuard1;
    ModelRenderer JointGuard2;
    ModelRenderer JointGuard3;
    ModelRenderer JointGuard4;


  
    public modelByakushiki()
    {
      textureWidth = 256;
      textureHeight = 256;
    
      head.mirror = true;
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(256, 256);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      head.mirror = false;
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 3);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(256, 256);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 40, 16);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(256, 256);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0.4363323F);
      leftarm = new ModelRenderer(this, 40, 16);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(256, 256);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, -0.4363323F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      rightleg.setRotationPoint(-2F, 12F, 0F);
      rightleg.setTextureSize(256, 256);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0.3490659F);
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      leftleg.setRotationPoint(2F, 12F, 0F);
      leftleg.setTextureSize(256, 256);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, -0.3490659F);
      RightShoulderGuardTop.mirror = true;
      RightShoulderGuardTop = new ModelRenderer(this, 0, 34);
      RightShoulderGuardTop.addBox(-8.5F, -3F, -3F, 8, 2, 6);
      RightShoulderGuardTop.setRotationPoint(-5F, 2F, 0F);
      RightShoulderGuardTop.setTextureSize(256, 256);
      RightShoulderGuardTop.mirror = true;
      setRotation(RightShoulderGuardTop, 0F, 0F, 0F);
      RightShoulderGuardTop.mirror = false;
      RightShoulderGuardFrontBack = new ModelRenderer(this, 0, 43);
      RightShoulderGuardFrontBack.addBox(-2.5F, -2.5F, -3.5F, 3, 3, 7);
      RightShoulderGuardFrontBack.setRotationPoint(-5F, 2F, 0F);
      RightShoulderGuardFrontBack.setTextureSize(256, 256);
      RightShoulderGuardFrontBack.mirror = true;
      setRotation(RightShoulderGuardFrontBack, 0F, 0F, 0F);
      RightFrontIncline1 = new ModelRenderer(this, 32, 34);
      RightFrontIncline1.addBox(-5F, -1.5F, -3F, 5, 1, 1);
      RightFrontIncline1.setRotationPoint(-5F, 2F, 0F);
      RightFrontIncline1.setTextureSize(256, 256);
      RightFrontIncline1.mirror = true;
      setRotation(RightFrontIncline1, 0F, 0F, 0F);
      RightFrontIncline2 = new ModelRenderer(this, 32, 37);
      RightFrontIncline2.addBox(-5.5F, -2F, -3F, 5, 1, 1);
      RightFrontIncline2.setRotationPoint(-5F, 2F, 0F);
      RightFrontIncline2.setTextureSize(256, 256);
      RightFrontIncline2.mirror = true;
      setRotation(RightFrontIncline2, 0F, 0F, 0F);
      RightFrontIncline3 = new ModelRenderer(this, 32, 40);
      RightFrontIncline3.addBox(-6F, -2.5F, -3F, 5, 1, 1);
      RightFrontIncline3.setRotationPoint(-5F, 2F, 0F);
      RightFrontIncline3.setTextureSize(256, 256);
      RightFrontIncline3.mirror = true;
      setRotation(RightFrontIncline3, 0F, 0F, 0F);
      RightFrontIncline4 = new ModelRenderer(this, 32, 43);
      RightFrontIncline4.addBox(-6.5F, -3F, -3F, 5, 1, 1);
      RightFrontIncline4.setRotationPoint(-5F, 2F, 0F);
      RightFrontIncline4.setTextureSize(256, 256);
      RightFrontIncline4.mirror = true;
      setRotation(RightFrontIncline4, 0F, 0F, 0F);
      RightFrontIncline5 = new ModelRenderer(this, 32, 46);
      RightFrontIncline5.addBox(-7F, -3.5F, -3F, 5, 1, 1);
      RightFrontIncline5.setRotationPoint(-5F, 2F, 0F);
      RightFrontIncline5.setTextureSize(256, 256);
      RightFrontIncline5.mirror = true;
      setRotation(RightFrontIncline5, 0F, 0F, 0F);
      RightFrontIncline6 = new ModelRenderer(this, 32, 49);
      RightFrontIncline6.addBox(-7.5F, -4F, -3F, 5, 1, 1);
      RightFrontIncline6.setRotationPoint(-5F, 2F, 0F);
      RightFrontIncline6.setTextureSize(256, 256);
      RightFrontIncline6.mirror = true;
      setRotation(RightFrontIncline6, 0F, 0F, 0F);
      RightBackIncline1 = new ModelRenderer(this, 32, 34);
      RightBackIncline1.addBox(-5F, -1.5F, 2F, 5, 1, 1);
      RightBackIncline1.setRotationPoint(-5F, 2F, 0F);
      RightBackIncline1.setTextureSize(256, 256);
      RightBackIncline1.mirror = true;
      setRotation(RightBackIncline1, 0F, 0F, 0F);
      RightBackIncline2 = new ModelRenderer(this, 32, 37);
      RightBackIncline2.addBox(-5.5F, -2F, 2F, 5, 1, 1);
      RightBackIncline2.setRotationPoint(-5F, 2F, 0F);
      RightBackIncline2.setTextureSize(256, 256);
      RightBackIncline2.mirror = true;
      setRotation(RightBackIncline2, 0F, 0F, 0F);
      RightBackIncline3 = new ModelRenderer(this, 32, 40);
      RightBackIncline3.addBox(-6F, -2.5F, 2F, 5, 1, 1);
      RightBackIncline3.setRotationPoint(-5F, 2F, 0F);
      RightBackIncline3.setTextureSize(256, 256);
      RightBackIncline3.mirror = true;
      setRotation(RightBackIncline3, 0F, 0F, 0F);
      RightBackIncline4 = new ModelRenderer(this, 32, 43);
      RightBackIncline4.addBox(-6.5F, -3F, 2F, 5, 1, 1);
      RightBackIncline4.setRotationPoint(-5F, 2F, 0F);
      RightBackIncline4.setTextureSize(256, 256);
      RightBackIncline4.mirror = true;
      setRotation(RightBackIncline4, 0F, 0F, 0F);
      RightBackIncline5 = new ModelRenderer(this, 32, 46);
      RightBackIncline5.addBox(-7F, -3.5F, 2F, 5, 1, 1);
      RightBackIncline5.setRotationPoint(-5F, 2F, 0F);
      RightBackIncline5.setTextureSize(256, 256);
      RightBackIncline5.mirror = true;
      setRotation(RightBackIncline5, 0F, 0F, 0F);
      RightBackIncline6 = new ModelRenderer(this, 32, 49);
      RightBackIncline6.addBox(-7.5F, -4F, 2F, 5, 1, 1);
      RightBackIncline6.setRotationPoint(-5F, 2F, 0F);
      RightBackIncline6.setTextureSize(256, 256);
      RightBackIncline6.mirror = true;
      setRotation(RightBackIncline6, 0F, 0F, 0F);
      RightJointGuard1 = new ModelRenderer(this, 0, 54);
      RightJointGuard1.addBox(-4.9F, -0.5F, -3F, 2, 5, 6);
      RightJointGuard1.setRotationPoint(0F, 0F, 0F);
      RightJointGuard1.setTextureSize(256, 256);
      RightJointGuard1.mirror = true;
      setRotation(RightJointGuard1, 0F, 0F, 0F);
      RightJointGuard2 = new ModelRenderer(this, 0, 66);
      RightJointGuard2.addBox(-3.1F, 0F, -3F, 1, 3, 6);
      RightJointGuard2.setRotationPoint(0F, 0F, 0F);
      RightJointGuard2.setTextureSize(256, 256);
      RightJointGuard2.mirror = true;
      setRotation(RightJointGuard2, 0F, 0F, 0F);
      RightJointGuard3 = new ModelRenderer(this, 0, 76);
      RightJointGuard3.addBox(-2.1F, 0F, -3F, 1, 2, 6);
      RightJointGuard3.setRotationPoint(0F, 0F, 0F);
      RightJointGuard3.setTextureSize(256, 256);
      RightJointGuard3.mirror = true;
      setRotation(RightJointGuard3, 0F, 0F, 0F);
      RightJointGuard4 = new ModelRenderer(this, 0, 85);
      RightJointGuard4.addBox(-1.4F, 2.3F, -3F, 1, 3, 6);
      RightJointGuard4.setRotationPoint(0F, 0F, 0F);
      RightJointGuard4.setTextureSize(256, 256);
      RightJointGuard4.mirror = true;
      setRotation(RightJointGuard4, 0F, 0F, 0F);
      BackTop = new ModelRenderer(this, 0, 95);
      BackTop.addBox(-4F, 0F, 0.1F, 8, 6, 1);
      BackTop.setRotationPoint(0F, 0F, 2F);
      BackTop.setTextureSize(256, 256);
      BackTop.mirror = true;
      setRotation(BackTop, 0F, 0F, 0F);
      BackMiddle = new ModelRenderer(this, 0, 103);
      BackMiddle.addBox(-2F, 5F, -0.5F, 4, 3, 1);
      BackMiddle.setRotationPoint(0F, 0F, 2F);
      BackMiddle.setTextureSize(256, 256);
      BackMiddle.mirror = true;
      setRotation(BackMiddle, 0F, 0F, 0F);
      Abdomen = new ModelRenderer(this, -1, 108);
      Abdomen.addBox(-4F, 7F, -2.5F, 8, 5, 5);
      Abdomen.setRotationPoint(0F, 0F, 0F);
      Abdomen.setTextureSize(256, 256);
      Abdomen.mirror = true;
      setRotation(Abdomen, 0F, 0F, 0F);
      FrontMiddleRight = new ModelRenderer(this, 32, 54);
      FrontMiddleRight.addBox(-5F, 6.5F, -3F, 4, 1, 6);
      FrontMiddleRight.setRotationPoint(0F, 0F, 0F);
      FrontMiddleRight.setTextureSize(256, 256);
      FrontMiddleRight.mirror = true;
      setRotation(FrontMiddleRight, 0F, 0F, 0F);
      FrontMiddleLeft = new ModelRenderer(this, 32, 54);
      FrontMiddleLeft.addBox(1F, 6.5F, -3F, 4, 1, 6);
      FrontMiddleLeft.setRotationPoint(0F, 0F, 0F);
      FrontMiddleLeft.setTextureSize(256, 256);
      FrontMiddleLeft.mirror = true;
      setRotation(FrontMiddleLeft, 0F, 0F, 0F);
      Waist = new ModelRenderer(this, 0, 138);
      Waist.addBox(-4.5F, 11F, -2F, 9, 1, 4);
      Waist.setRotationPoint(0F, 0F, 0F);
      Waist.setTextureSize(256, 256);
      Waist.mirror = true;
      setRotation(Waist, 0F, 0F, 0F);
      LeftArmBase = new ModelRenderer(this, 0, 122);
      LeftArmBase.addBox(-1.5F, 5.5F, -2.5F, 5, 9, 5);
      LeftArmBase.setRotationPoint(5F, 2F, 0F);
      LeftArmBase.setTextureSize(256, 256);
      LeftArmBase.mirror = true;
      setRotation(LeftArmBase, 0F, 0F, 0F);
      LeftArmVent = new ModelRenderer(this, 32, 98);
      LeftArmVent.addBox(3.5F, 3.5F, -3F, 2, 9, 6);
      LeftArmVent.setRotationPoint(5F, 2F, 0F);
      LeftArmVent.setTextureSize(256, 256);
      LeftArmVent.mirror = true;
      setRotation(LeftArmVent, 0F, 0F, 0F);
      LeftArmGuardTop = new ModelRenderer(this, 32, 80);
      LeftArmGuardTop.addBox(3F, 8F, -3.5F, 3, 9, 7);
      LeftArmGuardTop.setRotationPoint(5F, 2F, 0F);
      LeftArmGuardTop.setTextureSize(256, 256);
      LeftArmGuardTop.mirror = true;
      setRotation(LeftArmGuardTop, 0F, 0F, 0F);
      LeftArmGuardFront = new ModelRenderer(this, 32, 115);
      LeftArmGuardFront.addBox(2F, 13F, -3F, 1, 3, 1);
      LeftArmGuardFront.setRotationPoint(5F, 2F, 0F);
      LeftArmGuardFront.setTextureSize(256, 256);
      LeftArmGuardFront.mirror = true;
      setRotation(LeftArmGuardFront, 0F, 0F, 0F);
      LeftArmGuardBack = new ModelRenderer(this, 37, 115);
      LeftArmGuardBack.addBox(2F, 13F, 2F, 1, 3, 1);
      LeftArmGuardBack.setRotationPoint(5F, 2F, 0F);
      LeftArmGuardBack.setTextureSize(256, 256);
      LeftArmGuardBack.mirror = true;
      setRotation(LeftArmGuardBack, 0F, 0F, 0F);
      RightArmBase = new ModelRenderer(this, 0, 122);
      RightArmBase.addBox(-3.5F, 5.5F, -2.5F, 5, 9, 5);
      RightArmBase.setRotationPoint(-5F, 2F, 0F);
      RightArmBase.setTextureSize(256, 256);
      RightArmBase.mirror = true;
      setRotation(RightArmBase, 0F, 0F, 0F);
      RightArmVent.mirror = true;
      RightArmVent = new ModelRenderer(this, 32, 98);
      RightArmVent.addBox(-14.5F, 7.5F, -3F, 2, 9, 6);
      RightArmVent.setRotationPoint(5F, 2F, 0F);
      RightArmVent.setTextureSize(256, 256);
      RightArmVent.mirror = true;
      setRotation(RightArmVent, 0F, 0F, 0F);
      RightArmVent.mirror = false;
      RightArmGuardTop.mirror = true;
      RightArmGuardTop = new ModelRenderer(this, 32, 80);
      RightArmGuardTop.addBox(-15F, 12F, -3.5F, 3, 9, 7);
      RightArmGuardTop.setRotationPoint(5F, 2F, 0F);
      RightArmGuardTop.setTextureSize(256, 256);
      RightArmGuardTop.mirror = true;
      setRotation(RightArmGuardTop, 0F, 0F, 0F);
      RightArmGuardTop.mirror = false;
      RightArmGuardFront = new ModelRenderer(this, 32, 115);
      RightArmGuardFront.addBox(-3F, 13F, -3F, 1, 3, 1);
      RightArmGuardFront.setRotationPoint(-5F, 2F, 0F);
      RightArmGuardFront.setTextureSize(256, 256);
      RightArmGuardFront.mirror = true;
      setRotation(RightArmGuardFront, 0F, 0F, 0F);
      RightArmGuardBack = new ModelRenderer(this, 37, 115);
      RightArmGuardBack.addBox(-3F, 13F, 2F, 1, 3, 1);
      RightArmGuardBack.setRotationPoint(-5F, 2F, 0F);
      RightArmGuardBack.setTextureSize(256, 256);
      RightArmGuardBack.mirror = true;
      setRotation(RightArmGuardBack, 0F, 0F, 0F);
      LeftLegBase = new ModelRenderer(this, 32, 122);
      LeftLegBase.addBox(-2.5F, 6F, -2.5F, 5, 11, 5);
      LeftLegBase.setRotationPoint(2F, 12F, 0F);
      LeftLegBase.setTextureSize(256, 256);
      LeftLegBase.mirror = true;
      setRotation(LeftLegBase, 0F, 0F, 0F);
      LeftLegBaseSide = new ModelRenderer(this, 32, 140);
      LeftLegBaseSide.addBox(1.5F, 3F, -2.5F, 1, 3, 5);
      LeftLegBaseSide.setRotationPoint(2F, 12F, 0F);
      LeftLegBaseSide.setTextureSize(256, 256);
      LeftLegBaseSide.mirror = true;
      setRotation(LeftLegBaseSide, 0F, 0F, 0F);
      LeftLegBaseFrontTop = new ModelRenderer(this, 32, 149);
      LeftLegBaseFrontTop.addBox(-1F, 4F, -4.3F, 2, 5, 1);
      LeftLegBaseFrontTop.setRotationPoint(2F, 12F, 0F);
      LeftLegBaseFrontTop.setTextureSize(256, 256);
      LeftLegBaseFrontTop.mirror = true;
      setRotation(LeftLegBaseFrontTop, 0F, 0F, 0F);
      LeftLegBaseInside = new ModelRenderer(this, 0, 195);
      LeftLegBaseInside.addBox(-3F, 5.5F, -2.5F, 1, 12, 5);
      LeftLegBaseInside.setRotationPoint(2F, 12F, 0F);
      LeftLegBaseInside.setTextureSize(256, 256);
      LeftLegBaseInside.mirror = true;
      setRotation(LeftLegBaseInside, 0F, 0F, 0F);
      LeftLegBaseOutside = new ModelRenderer(this, 0, 175);
      LeftLegBaseOutside.addBox(2F, 4.5F, -2.5F, 1, 13, 5);
      LeftLegBaseOutside.setRotationPoint(2F, 12F, 0F);
      LeftLegBaseOutside.setTextureSize(256, 256);
      LeftLegBaseOutside.mirror = true;
      setRotation(LeftLegBaseOutside, 0F, 0F, 0F);
      FootJoint1 = new ModelRenderer(this, 0, 214);
      FootJoint1.addBox(-1.5F, 17F, -1.5F, 3, 1, 3);
      FootJoint1.setRotationPoint(2F, 12F, 0F);
      FootJoint1.setTextureSize(256, 256);
      FootJoint1.mirror = true;
      setRotation(FootJoint1, 0F, 0F, 0F);
      FootJoint2 = new ModelRenderer(this, 0, 167);
      FootJoint2.addBox(-2F, 17.5F, -3.5F, 4, 1, 6);
      FootJoint2.setRotationPoint(2F, 12F, 0F);
      FootJoint2.setTextureSize(256, 256);
      FootJoint2.mirror = true;
      setRotation(FootJoint2, 0F, 0F, 0F);
      FootJoint3 = new ModelRenderer(this, 0, 157);
      FootJoint3.addBox(-3F, 18.3F, -4.5F, 6, 1, 7);
      FootJoint3.setRotationPoint(2F, 12F, 0F);
      FootJoint3.setTextureSize(256, 256);
      FootJoint3.mirror = true;
      setRotation(FootJoint3, 0F, 0F, 0F);
      FootJoint4 = new ModelRenderer(this, 0, 146);
      FootJoint4.addBox(-3F, 18.7F, -5.5F, 6, 1, 8);
      FootJoint4.setRotationPoint(2F, 12F, 0F);
      FootJoint4.setTextureSize(256, 256);
      FootJoint4.mirror = true;
      setRotation(FootJoint4, 0F, 0F, 0F);
      RightLegBase = new ModelRenderer(this, 32, 122);
      RightLegBase.addBox(-2.5F, 6F, -2.5F, 5, 11, 5);
      RightLegBase.setRotationPoint(-2F, 12F, 0F);
      RightLegBase.setTextureSize(256, 256);
      RightLegBase.mirror = true;
      setRotation(RightLegBase, 0F, 0F, 0F);
      RightLegBaseSide = new ModelRenderer(this, 32, 140);
      RightLegBaseSide.addBox(-2.5F, 3F, -2.5F, 1, 3, 5);
      RightLegBaseSide.setRotationPoint(-2F, 12F, 0F);
      RightLegBaseSide.setTextureSize(256, 256);
      RightLegBaseSide.mirror = true;
      setRotation(RightLegBaseSide, 0F, 0F, 0F);
      RightLegBaseFrontTop = new ModelRenderer(this, 32, 149);
      RightLegBaseFrontTop.addBox(-1F, 4F, -4.3F, 2, 5, 1);
      RightLegBaseFrontTop.setRotationPoint(-2F, 12F, 0F);
      RightLegBaseFrontTop.setTextureSize(256, 256);
      RightLegBaseFrontTop.mirror = true;
      setRotation(RightLegBaseFrontTop, 0.1570796F, 0F, 0F);
      RightLegBaseInside = new ModelRenderer(this, 0, 195);
      RightLegBaseInside.addBox(2F, 5.5F, -2.5F, 1, 12, 5);
      RightLegBaseInside.setRotationPoint(-2F, 12F, 0F);
      RightLegBaseInside.setTextureSize(256, 256);
      RightLegBaseInside.mirror = true;
      setRotation(RightLegBaseInside, 0F, 0F, 0F);
      RightLegBaseOutside = new ModelRenderer(this, 0, 175);
      RightLegBaseOutside.addBox(-3F, 4.5F, -2.5F, 1, 13, 5);
      RightLegBaseOutside.setRotationPoint(-2F, 12F, 0F);
      RightLegBaseOutside.setTextureSize(256, 256);
      RightLegBaseOutside.mirror = true;
      setRotation(RightLegBaseOutside, 0F, 0F, 0F);
      RightFootJoint1 = new ModelRenderer(this, 0, 214);
      RightFootJoint1.addBox(-1.5F, 17F, -1.5F, 3, 1, 3);
      RightFootJoint1.setRotationPoint(-2F, 12F, 0F);
      RightFootJoint1.setTextureSize(256, 256);
      RightFootJoint1.mirror = true;
      setRotation(RightFootJoint1, 0F, 0F, 0F);
      RightFootJoint2 = new ModelRenderer(this, 0, 167);
      RightFootJoint2.addBox(-2F, 17.5F, -3.5F, 4, 1, 6);
      RightFootJoint2.setRotationPoint(-2F, 12F, 0F);
      RightFootJoint2.setTextureSize(256, 256);
      RightFootJoint2.mirror = true;
      setRotation(RightFootJoint2, 0F, 0F, 0F);
      RightFootJoint3 = new ModelRenderer(this, 0, 157);
      RightFootJoint3.addBox(-3F, 18.3F, -4.5F, 6, 1, 7);
      RightFootJoint3.setRotationPoint(-2F, 12F, 0F);
      RightFootJoint3.setTextureSize(256, 256);
      RightFootJoint3.mirror = true;
      setRotation(RightFootJoint3, 0F, 0F, 0F);
      RightFootJoint4 = new ModelRenderer(this, 0, 146);
      RightFootJoint4.addBox(-3F, 18.7F, -5.5F, 6, 1, 8);
      RightFootJoint4.setRotationPoint(-2F, 12F, 0F);
      RightFootJoint4.setTextureSize(256, 256);
      RightFootJoint4.mirror = true;
      setRotation(RightFootJoint4, 0F, 0F, 0F);
      HelmetBack = new ModelRenderer(this, 32, 76);
      HelmetBack.addBox(-2F, -6.85F, 3.5F, 4, 1, 1);
      HelmetBack.setRotationPoint(0F, 0F, 0F);
      HelmetBack.setTextureSize(256, 256);
      HelmetBack.mirror = true;
      setRotation(HelmetBack, 0F, 0F, 0F);
      HelmetLeft = new ModelRenderer(this, 32, 64);
      HelmetLeft.addBox(2.5F, -6.5F, -4.5F, 3, 1, 9);
      HelmetLeft.setRotationPoint(0F, 0F, 0F);
      HelmetLeft.setTextureSize(256, 256);
      HelmetLeft.mirror = true;
      setRotation(HelmetLeft, 0F, 0F, 0F);
      HelmetRight = new ModelRenderer(this, 32, 64);
      HelmetRight.addBox(-5.5F, -6.5F, -4.5F, 3, 1, 9);
      HelmetRight.setRotationPoint(0F, 0F, 0F);
      HelmetRight.setTextureSize(256, 256);
      HelmetRight.mirror = true;
      setRotation(HelmetRight, 0F, 0F, 0F);
      ShoulderGuardTop = new ModelRenderer(this, 0, 34);
      ShoulderGuardTop.addBox(0.5F, -3F, -3F, 8, 2, 6);
      ShoulderGuardTop.setRotationPoint(5F, 2F, 0F);
      ShoulderGuardTop.setTextureSize(256, 256);
      ShoulderGuardTop.mirror = true;
      setRotation(ShoulderGuardTop, 0F, 0F, 0F);
      ShoulderGuardFrontBack = new ModelRenderer(this, 0, 43);
      ShoulderGuardFrontBack.addBox(-0.5F, -2.5F, -3.5F, 3, 3, 7);
      ShoulderGuardFrontBack.setRotationPoint(5F, 2F, 0F);
      ShoulderGuardFrontBack.setTextureSize(256, 256);
      ShoulderGuardFrontBack.mirror = true;
      setRotation(ShoulderGuardFrontBack, 0F, 0F, 0F);
      FrontIncline1 = new ModelRenderer(this, 32, 34);
      FrontIncline1.addBox(0F, -1.5F, -3F, 5, 1, 1);
      FrontIncline1.setRotationPoint(5F, 2F, 0F);
      FrontIncline1.setTextureSize(256, 256);
      FrontIncline1.mirror = true;
      setRotation(FrontIncline1, 0F, 0F, 0F);
      FrontIncline2 = new ModelRenderer(this, 32, 37);
      FrontIncline2.addBox(0.5F, -2F, -3F, 5, 1, 1);
      FrontIncline2.setRotationPoint(5F, 2F, 0F);
      FrontIncline2.setTextureSize(256, 256);
      FrontIncline2.mirror = true;
      setRotation(FrontIncline2, 0F, 0F, 0F);
      FrontIncline3 = new ModelRenderer(this, 32, 40);
      FrontIncline3.addBox(1F, -2.5F, -3F, 5, 1, 1);
      FrontIncline3.setRotationPoint(5F, 2F, 0F);
      FrontIncline3.setTextureSize(256, 256);
      FrontIncline3.mirror = true;
      setRotation(FrontIncline3, 0F, 0F, 0F);
      FrontIncline4 = new ModelRenderer(this, 32, 43);
      FrontIncline4.addBox(1.5F, -3F, -3F, 5, 1, 1);
      FrontIncline4.setRotationPoint(5F, 2F, 0F);
      FrontIncline4.setTextureSize(256, 256);
      FrontIncline4.mirror = true;
      setRotation(FrontIncline4, 0F, 0F, 0F);
      FrontIncline5 = new ModelRenderer(this, 32, 46);
      FrontIncline5.addBox(2F, -3.5F, -3F, 5, 1, 1);
      FrontIncline5.setRotationPoint(5F, 2F, 0F);
      FrontIncline5.setTextureSize(256, 256);
      FrontIncline5.mirror = true;
      setRotation(FrontIncline5, 0F, 0F, 0F);
      FrontIncline6 = new ModelRenderer(this, 32, 49);
      FrontIncline6.addBox(3.5F, -4F, -3F, 4, 1, 1);
      FrontIncline6.setRotationPoint(5F, 2F, 0F);
      FrontIncline6.setTextureSize(256, 256);
      FrontIncline6.mirror = true;
      setRotation(FrontIncline6, 0F, 0F, 0F);
      BackIncline1 = new ModelRenderer(this, 32, 34);
      BackIncline1.addBox(0F, -1.5F, 2F, 5, 1, 1);
      BackIncline1.setRotationPoint(5F, 2F, 0F);
      BackIncline1.setTextureSize(256, 256);
      BackIncline1.mirror = true;
      setRotation(BackIncline1, 0F, 0F, 0F);
      BackIncline2 = new ModelRenderer(this, 32, 37);
      BackIncline2.addBox(0.5F, -2F, 2F, 5, 1, 1);
      BackIncline2.setRotationPoint(5F, 2F, 0F);
      BackIncline2.setTextureSize(256, 256);
      BackIncline2.mirror = true;
      setRotation(BackIncline2, 0F, 0F, 0F);
      BackIncline3 = new ModelRenderer(this, 32, 40);
      BackIncline3.addBox(1F, -2.5F, 2F, 5, 1, 1);
      BackIncline3.setRotationPoint(5F, 2F, 0F);
      BackIncline3.setTextureSize(256, 256);
      BackIncline3.mirror = true;
      setRotation(BackIncline3, 0F, 0F, 0F);
      BackIncline4 = new ModelRenderer(this, 32, 43);
      BackIncline4.addBox(1.5F, -3F, 2F, 5, 1, 1);
      BackIncline4.setRotationPoint(5F, 2F, 0F);
      BackIncline4.setTextureSize(256, 256);
      BackIncline4.mirror = true;
      setRotation(BackIncline4, 0F, 0F, 0F);
      BackIncline5 = new ModelRenderer(this, 32, 46);
      BackIncline5.addBox(2F, -3.5F, 2F, 5, 1, 1);
      BackIncline5.setRotationPoint(5F, 2F, 0F);
      BackIncline5.setTextureSize(256, 256);
      BackIncline5.mirror = true;
      setRotation(BackIncline5, 0F, 0F, 0F);
      BackIncline6 = new ModelRenderer(this, 32, 49);
      BackIncline6.addBox(3.5F, -4F, 2F, 4, 1, 1);
      BackIncline6.setRotationPoint(5F, 2F, 0F);
      BackIncline6.setTextureSize(256, 256);
      BackIncline6.mirror = true;
      setRotation(BackIncline6, 0F, 0F, 0F);
      JointGuard1 = new ModelRenderer(this, 0, 54);
      JointGuard1.addBox(2.9F, -0.5F, -3F, 2, 5, 6);
      JointGuard1.setRotationPoint(0F, 0F, 0F);
      JointGuard1.setTextureSize(256, 256);
      JointGuard1.mirror = true;
      setRotation(JointGuard1, 0F, 0F, 0F);
      JointGuard2 = new ModelRenderer(this, 0, 66);
      JointGuard2.addBox(2.1F, 0F, -3F, 1, 3, 6);
      JointGuard2.setRotationPoint(0F, 0F, 0F);
      JointGuard2.setTextureSize(256, 256);
      JointGuard2.mirror = true;
      setRotation(JointGuard2, 0F, 0F, 0F);
      JointGuard3 = new ModelRenderer(this, 0, 76);
      JointGuard3.addBox(1.1F, 0F, -3F, 1, 2, 6);
      JointGuard3.setRotationPoint(0F, 0F, 0F);
      JointGuard3.setTextureSize(256, 256);
      JointGuard3.mirror = true;
      setRotation(JointGuard3, 0F, 0F, 0F);
      JointGuard4 = new ModelRenderer(this, 0, 85);
      JointGuard4.addBox(0.4F, 2.3F, -3F, 1, 3, 6);
      JointGuard4.setRotationPoint(0F, 0F, 0F);
      JointGuard4.setTextureSize(256, 256);
      JointGuard4.mirror = true;
      setRotation(JointGuard4, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
      super.render(entity, f, f1, f2, f3, f4, f5);
      setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      head.render(f5);
      body.render(f5);
      rightarm.render(f5);
      leftarm.render(f5);
      rightleg.render(f5);
      leftleg.render(f5);
      RightShoulderGuardTop.render(f5);
      RightShoulderGuardFrontBack.render(f5);
      RightFrontIncline1.render(f5);
      RightFrontIncline2.render(f5);
      RightFrontIncline3.render(f5);
      RightFrontIncline4.render(f5);
      RightFrontIncline5.render(f5);
      RightFrontIncline6.render(f5);
      RightBackIncline1.render(f5);
      RightBackIncline2.render(f5);
      RightBackIncline3.render(f5);
      RightBackIncline4.render(f5);
      RightBackIncline5.render(f5);
      RightBackIncline6.render(f5);
      RightJointGuard1.render(f5);
      RightJointGuard2.render(f5);
      RightJointGuard3.render(f5);
      RightJointGuard4.render(f5);
    BackTop.render(f5);
    BackMiddle.render(f5);
    Abdomen.render(f5);
    FrontMiddleRight.render(f5);
    FrontMiddleLeft.render(f5);
    Waist.render(f5);
    LeftArmBase.render(f5);
    LeftArmVent.render(f5);
    LeftArmGuardTop.render(f5);
    LeftArmGuardFront.render(f5);
    LeftArmGuardBack.render(f5);
    RightArmBase.render(f5);
    RightArmVent.render(f5);
    RightArmGuardTop.render(f5);
    RightArmGuardFront.render(f5);
    RightArmGuardBack.render(f5);
    LeftLegBase.render(f5);
    LeftLegBaseSide.render(f5);
    LeftLegBaseFrontTop.render(f5);
    LeftLegBaseInside.render(f5);
    LeftLegBaseOutside.render(f5);
    FootJoint1.render(f5);
    FootJoint2.render(f5);
    FootJoint3.render(f5);
    FootJoint4.render(f5);
    RightLegBase.render(f5);
    RightLegBaseSide.render(f5);
    RightLegBaseFrontTop.render(f5);
    RightLegBaseInside.render(f5);
    RightLegBaseOutside.render(f5);
    FootJoint1.render(f5);
    FootJoint2.render(f5);
    FootJoint3.render(f5);
    FootJoint4.render(f5);
    HelmetBack.render(f5);
    HelmetLeft.render(f5);
    HelmetRight.render(f5);
    ShoulderGuardTop.render(f5);
    ShoulderGuardFrontBack.render(f5);
    FrontIncline1.render(f5);
    FrontIncline2.render(f5);
    FrontIncline3.render(f5);
    FrontIncline4.render(f5);
    FrontIncline5.render(f5);
    FrontIncline6.render(f5);
    BackIncline1.render(f5);
    BackIncline2.render(f5);
    BackIncline3.render(f5);
    BackIncline4.render(f5);
    BackIncline5.render(f5);
    BackIncline6.render(f5);
    JointGuard1.render(f5);
    JointGuard2.render(f5);
    JointGuard3.render(f5);
    JointGuard4.render(f5);
    }
  
    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
    }
  
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }
}
